services:
  - type: web
    name: z4rum-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    autoDeploy: true
